# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(db_column='Complaint_id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
                ('replay', models.CharField(db_column='Replay', max_length=45)),
                ('complaint', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
