# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('exam_schedule_id', models.AutoField(db_column='Exam_Schedule_id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
                ('subject', models.CharField(db_column='Subject', max_length=45)),
            ],
            options={
                'db_table': 'exam_schedule',
                'managed': False,
            },
        ),
    ]
