# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('videos_id', models.AutoField(db_column='Videos_id', primary_key=True, serialize=False)),
                ('video_upload', models.TextField(db_column='Video_upload')),
            ],
            options={
                'db_table': 'videos',
                'managed': False,
            },
        ),
    ]
