# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='Payment_id', primary_key=True, serialize=False)),
                ('card_holder_name', models.CharField(db_column='Card_holder_Name', max_length=45)),
                ('card_number', models.CharField(db_column='Card_Number', max_length=45)),
                ('cvv', models.IntegerField(db_column='CVV')),
                ('amount', models.CharField(db_column='Amount', max_length=45)),
                ('status', models.CharField(db_column='Status', max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
