# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(db_column='Tutor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('place', models.CharField(db_column='Place', max_length=45)),
                ('gender', models.CharField(db_column='Gender', max_length=45)),
                ('dob', models.DateField(db_column='DOB')),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('pincode', models.IntegerField(db_column='Pincode')),
                ('phone_no', models.CharField(db_column='Phone_No', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('education', models.CharField(db_column='Education', max_length=45)),
                ('state', models.CharField(db_column='State', max_length=45)),
                ('availability', models.CharField(db_column='Availability', max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
    ]
