# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('studymaterial_id', models.AutoField(db_column='Studymaterial_id', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=45)),
                ('study_material', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'study_material',
                'managed': False,
            },
        ),
    ]
