# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('doubt_id', models.AutoField(db_column='Doubt_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=45)),
                ('date', models.DateField(db_column='Date')),
                ('replay', models.CharField(db_column='Replay', max_length=45)),
            ],
            options={
                'db_table': 'doubt',
                'managed': False,
            },
        ),
    ]
