# Generated by Django 3.2.25 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(db_column='Notification_id', primary_key=True, serialize=False)),
                ('notification', models.CharField(db_column='Notification', max_length=45)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
